name: MERN CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"

      # --- FIX IS HERE ---
      - name: Add execute permission to scripts
        run: |
          chmod +x backend/node_modules/.bin/jest
          chmod +x backend/node_modules/.bin/cucumber-js
      # --------------------
      - name: Run Backend Tests (Unit & BDD)
        run: |
          cd backend
          npm test
          npm run test:bdd
        env:
          MONGO_URI: mongodb://localhost:27017/testdb # Use the service DB

      - name: Check Frontend Directory Exists
        run: |
          if [ ! -f "frontend/package.json" ]; then
            echo "frontend/package.json not found. Skipping frontend steps."
            exit 0
          fi

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Run Frontend Tests
        run: cd frontend && npm test
        env:
          CI: true # Run tests in non-interactive mode

